version: '3.8'

services:
  # 1. Veritabanı (PostgreSQL)
  postgres:
    image: postgres:16
    container_name: otel-postgres
    restart: always
    ports:
      - "5432:5432" # Dışarıya 5432 ver (Payload buradan bağlanacak)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: otel-projesi
    volumes:
      - ./db_data:/var/lib/postgresql/data # Veriler kaybolmasın diye buraya kaydet

  # 2. Dosya Depolama (MinIO / S3)
  minio:
    image: minio/minio
    container_name: otel-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data